# Generated by Django 2.2 on 2020-04-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indianexpress', '0010_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='num',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
