# Generated by Django 2.2 on 2020-03-11 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indianexpress', '0004_signup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignUp',
        ),
    ]
