# Generated by Django 2.2 on 2020-03-12 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indianexpress', '0007_remove_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='signup_confirmation',
        ),
        migrations.AddField(
            model_name='profile',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
