# Generated by Django 2.2 on 2020-03-12 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indianexpress', '0008_auto_20200311_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='signup_confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
